### PR TITLE
Create Pratheeksha_naruto

### PR DESCRIPTION
**Pull request by 035pratheeksha**
As i'm doing it for the 1st time,Please look into this and add me as a contributor. Thank you.

### CODE REVIEW

**Comment by 035pratheeksha** [comment]
Please add me as a contributor for hacktoberfest.

**Comment by 035pratheeksha** [comment]
Did i not do the pull/merge request properly?

**Comment by 035pratheeksha** [comment]
Why i've not been accepted? @vikhyatsingh123

**Comment by vikhyatsingh123** [comment]
it's already accepted

**Comment by 035pratheeksha** [comment]
Ohh is it?
Did you add me as a contributor to hacktoberfest?

**Comment by vikhyatsingh123** [comment]
Are you new on Github or in hacktoberfest

**Comment by 035pratheeksha** [comment]
> Are you new on Github or in hacktoberfest

both.

**Comment by vikhyatsingh123** [comment]
OK, so register on hacktoberfest website first. There you will see your merged pr

**Comment by 035pratheeksha** [comment]
Ive registered..but its showing like its not accepted

**Comment by 035pratheeksha** [comment]
Screenshot (1935)

**Comment by vikhyatsingh123** [comment]
It's not mine PR. See the name sandeep

**Pull request merged**
